import tensorflow as tf
#s = tf.Variable(0, dtype=tf.int64, trainable=False)
#loss = tf.Variable(0, dtype=tf.float32)
#update = tf.train.AdamOptimizer().minimize(loss, global_step=s)
#sess = tf.Session()
#sess.run(tf.global_variables_initializer())
s = tf.get_variable('s', initializer=0)
s = tf.assign(s, s+1)
tf.add_to_collection(tf.GraphKeys.GLOBAL_STEP, s)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print sess.run(s)
print sess.run(s)
print sess.run(s)
